.TH DIGITD 8 
.SH NAME
digitd \- a simple and safe finger daemon for linux
.SH SYNOPSIS
.B digitd
.PP
.SH "DESCRIPTION"
.PP
.B digitd
is a simple and safe finger daemon, ready-to-run out of the box, yet
easy to customize. It allows users to opt in to being fingerable,
rather than the usual opt-out.
.SH USAGE
.PP
Digitd should be run from inetd. See README for setup information.
.PP
The following executables provide information to the fingerer:
.TP
/etc/digitd/list
run to answer a list request (finger @your.machine)
.TP
/etc/digitd/user
run when a user with a ~/.finger file is fingered
.TP
/etc/digitd/nouser
run when a non-existent user or user without a ~/.finger file is fingered
.PP
Each program is called with a single parameter, the name of the local
user being fingered, and should print the desired information on
standard output.
.SH "SEE ALSO"
finger(1), inetd(8)
.SH AUTHOR
Reuben Thomas (rrt@sc3d.org)
