.TH EFINGERD 8 
.SH NAME
efingerd \- another finger daemon for linux
.SH SYNOPSIS
.B efingerd
.I "[--help] [--version]"

efingerd should be run from inetd.

.SH "DESCRIPTION"
.B efingerd
is another finger daemon, giving you complete control over what
are you going to display about your computer.
.PP
.SH OPTIONS
.TP
.B \-\-help
Show summary of options and exit.
.TP
.B \-\-version
Show version and exit.
.SH USAGE
The following executables provide information to the fingerer:
   
/etc/efingerd/list
  what to display when somebody does finger @your.machine

/etc/efingerd/luser
  what to display when somebody a fingers a user with a ~/.finger file

/etc/efingerd/nouser
  what to display when somebody fingers a non-existent user

These are normal programs, displaying on standard output desired 
information. These programs are called with following parameters:
  $1 - address of remote machine (IP number if it has not reverse DNS 
entry)
  $2 - name of local user being fingered

Look at examples/ for examples.
Don't forget that these programs must be executable by the efingerd daemon.
.SH "SEE ALSO"
finger(1), fingerd(8)
.SH AUTHOR
Radovan Garabik (garabik@fmph.uniba.sk)
