DESTDIR =
BINDIR=$(DESTDIR)/usr/sbin
MANDIR=$(DESTDIR)/usr/man/man8	

all: efingerd

clean:
	rm -f *~ *.o efingerd

install: efingerd 
	cp efingerd $(BINDIR)
	mkdir -p $(DESTDIR)/etc/efingerd
	cp examples/* $(DESTDIR)/etc/efingerd
