DESTDIR =
BINDIR=$(DESTDIR)/usr/sbin
MANDIR=$(DESTDIR)/usr/man/man8	

CC = gcc 
CFLAGS = -O2 -Wall  

LIBS = -lident

all: efingerd

efingerd: efingerd.o child.o
	$(CC) $(CFLAGS) $(LDFLAGS) efingerd.o child.o -o efingerd $(LIBS)

efingerd.o: efingerd.c
	$(CC) $(CFLAGS) -c efingerd.c

child.o: child.c
	$(CC) $(CFLAGS) -c child.c

clean:
	rm -f *~ *.o efingerd

install: efingerd 
	cp efingerd $(BINDIR)
	mkdir -p $(DESTDIR)/etc/efingerd
	cp examples-standard/* $(DESTDIR)/etc/efingerd
