#!/bin/sh  -e
# postinst for djbdns
# written by Adam McKenna
# <adam@debian.org>

#DEBCONF_DEBUG=1
#export DEBCONF_DEBUG

case "$1" in
    configure)
	# continue below
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
	exit 0
    ;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 0
    ;;
esac


umask 022

# add daemon user

if ! grep -q '^digitd:' /etc/passwd; then 
    adduser --quiet --system --no-create-home --disabled-password --home /etc/digitd --gecos "digitd daemon" digitd
fi

# create log file

LOGFILE=/var/log/digitd.log
if [ ! -f $LOGFILE ]; then 
  touch $LOGFILE
  chmod 0644 $LOGFILE
  chown digitd:adm $LOGFILE
fi

update-inetd --remove 'finger\t.*'
update-inetd --group INFO --add "finger		stream	tcp	nowait	digitd	/usr/sbin/tcpd	/usr/sbin/digitd"

exit 0
