#!/bin/sh

. /etc/efingerd/log  # do some logging

echo

if [ "$1" = "pascal.fmph.uniba.sk" ]; then # ban the whole computer pascal
  echo "Sorry, we do not want you to know who is here."
  exit 0
fi

echo Hello "$1",

echo users currently logged in are:
echo
who -uHw        # and display the user listing in readable form
                 # or:
# finger         # classical alternative
                 # or:
# ps aux         # this reveals too much - do not use this command, unless 
                 # you trust people who finger you
echo
