#!/bin/sh

# Giving a list of users is a privacy and security risk
#echo "Users currently logged in are:"
#echo
#who -uHw        # and display the user listing in readable form
#                # or:
## finger        # classical alternative

echo "Finger online user list denied"