#!/bin/sh
# Privacy and security-respecting finger output
# Mimics output of finger, but only prints full name, PGP key, project
# and plan

USER=$1
passwd_record=$(getent passwd $USER)
gecos_field=$(echo "$passwd_record" | cut -d ':' -f 5)
HOME=$(echo "$passwd_record" | cut -d ':' -f 6)
full_name=$(echo "$gecos_field" | cut -d ',' -f 1)
pgpkey=$HOME/.pgpkey
project=$HOME/.project
plan=$HOME/.plan
printf "Name: $full_name\n"

if test -r $pgpkey; then
  printf "PGP key:\n"
  cat $pgpkey
fi

if test -r $project; then
  printf "Project:\n"
  cat $project
fi

if test -r $plan; then
  printf "Plan:\n"
  cat $plan
fi
