#!/bin/sh

. /etc/efingerd/log 

echo
echo -n Hello $1,\ 

if [ "$2" = "root" ]; then
  echo I am sorry, but root does not want to be fingered.
else
  echo "this is our dear user $2:"
  /usr/bin/finger "$2"
fi
