#!/bin/bash


. /etc/efingerd/log 

cat <<EOM

Microsoft Windows 95 finger daemon
     The ultimate experience.

 Who do you want to finger today?

EOM

if [ $RANDOM -le 16000 ]; then
cat <<EOM

MS fingerd caused general protection fault in address 0F44A34100:55F0321E

EOM
else
  cat <<EOM

The user logged here is:
 Windows caused protection error in module IO.SYS
 You may need to restart your computer.

EOM

fi

